[package]
name = "binartia_core"
version = "0.1.0"
edition = "2021"

[lib]
name = "binartia_core"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.22", features = ["extension-module"] }
numpy = "0.22"
rayon = "1.10"
